
const STATUS = {
    IDLE: 'IDLE',
    LOADING: 'LOADING',
    SUCCESS: 'SUCCESS',
    FAILURE: 'FAILURE',
    PENDING: 'PENDING',
    PROCESSING: 'PROCESSING',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED',
    DELIVERED: 'DELIVERED',
    SHIPPED: 'SHIPPED',
    REFUNDED: 'REFUNDED',
}

export default STATUS;