name: Build Client

on:
  workflow_run:
    workflows: ["Deploy Server"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm i -g vercel

      - name: Pull Vercel Secrets
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Install Client Dependencies
        run: |
          cd client
          npm install

      - name: Build Client
        run: |
          cd client
          npm run build
