name: Build Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: |
          cd server
          npm install
          cd ..
          cd client
          npm install
          npm run build

          # Check if PM2 process with ID 0 is running
          if pm2 jlist | grep -q '"pm_id":0'; then
            pm2 stop 0
          fi

          pm2 start 0
          pm2 save
          sudo service nginx restart

        env:
          CI: true

      - name: Run Tests
        run: |
          cd server
          npm run test
